### ISSUE TITLE
Is there for version Virtools v5.0?

### ISSUE THREAD

**Issue by Hellioob** [BearKidsTeam/VirtoolsScriptDeobfuscation#6]
I can't find Virtools 3.5 SDK anywhere!
Is there a way to use "VirtoolsScriptDeobfuscation" for version 5.0?

**Comment by yyc12345** [comment]
Sorry, there is no way to run this project in Virtools 5. Because the internal data layout of Virtools Behavior has been changed. The only solution to run this project on Virtools 5 is re-analyze Virtools Behavior in Virtools 5 environment. But it will cost too much time.
This project originally is served for the reverse work of Ballance, a rolling ball game created with Virtools 2.1. So obviously, supporting Virtools 5 is not the priority aim of this project. This project can run on Virtools 2.5 and Virtools 3.5 according to my test.

However, if you just want a Virtools 3.5 SDK. I can share for you. https://mega.nz/#F!CV5SyapR!LbduTW51xmkDO4EDxMfH9w
Download `Virtools - For programmer/Virtools 3.5 SDK.zip`, and extract it. This Mega link is also the resources link of Ballance Community.

**Comment by Hellioob** [comment]
Thanks for the link! Unfortunately I can't build due to many errors. It is too complicated for me to fix the errors that are getting during debug/build.

By any chance have an application ready with VirtoolsScriptDeobfuscation enabled?

**Comment by yyc12345** [comment]
Some configurations, such as log folder path, are hardcoded in this plugin. So I highly recommand that build it by yourself, **exactly** follwing the Build chapter of [README](https://github.com/BearKidsTeam/VirtoolsScriptDeobfuscation#build).
Use **Debug | Win32** configuration to build, otherwise, massive compile errors will be thrown.

However, if you still got some errors when compiling this project. I have a pre-compiled plugin for you. Decompress it and put that dll file into `BuildingBlocks` folder of Virtools root path. [Custom.zip](https://github.com/BearKidsTeam/VirtoolsScriptDeobfuscation/files/10739270/Custom.zip)
BUT, you **must** create 2 folders before using this plugin, `C:\test\generator` and `C:\test\parser`. The reason was said in Build chapter of README. Otherwise a runtime IO error will be thrown when using this plugin.

The usage of this plugin only has been written in README_ZH. There is a Google Translated version for your view.
> Create a new Virtools file, add a script at will, drag the Building Block (BB) BBDecoder on the Schematic, and drag and drop the starting point of the script to In 0 of the BB. Then double-click to edit the only Parameter, set it to the address of the file that needs to be reversed (it needs to be in an editable format, please use other tools to convert the VMO format into an editable file before executing), and then click the lower right corner to run the script You can start decompiling. The result of decompilation will be written to the current document immediately.
> Note: Whether you are debugging this BB or using this BB, the log file storage directory previously set in the code parameter adjustment cannot be deleted, so it is best to choose a suitable log storage location before compiling.

**Comment by Hellioob** [comment]
Thanks! Now it's working! :)
